In [1]:
import numpy as np
from keras import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [2]:
props_vectors_splitted=pd.read_csv('props_vectors.csv')
# There are 12 rows per one row of data consisting of 72 features.
# Drop the first 3 colums and merge 12 rows with different direction and angle 
# into one row of features for given sample.
props_vectors=props_vectors_splitted.iloc[:, 3:].values.reshape(-1, 12*6)
labels=props_vectors_splitted['texture_type'][::12]

In [3]:
label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(labels)
onehot_encoder=OneHotEncoder()
oneshot_encoded=onehot_encoder.fit_transform(integer_encoded.reshape(-1,1))
X_train, X_test, y_train, y_test=train_test_split(props_vectors, oneshot_encoded.toarray(), test_size=0.3)

In [4]:
model=Sequential()

model.add(Dense(10, input_dim=72, activation='sigmoid'))
model.add(Dense(4, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

c:\Users\rosia\.pyenv\pyenv-win\versions\3.10.11\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │           730 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            44 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 774 (3.02 KB)

 Trainable params: 774 (3.02 KB)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.fit(X_train, y_train, epochs=100, batch_size=10, shuffle=True)

Epoch 1/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 1s 955us/step - accuracy: 0.4956 - loss: 1.2660
Epoch 2/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.5538 - loss: 1.1303
Epoch 3/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.5383 - loss: 1.1168
Epoch 4/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5431 - loss: 1.0458
Epoch 5/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5555 - loss: 1.0097
Epoch 6/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5261 - loss: 1.0044  
Epoch 7/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5450 - loss: 0.9827  
Epoch 8/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.5570 - loss: 0.9137
Epoch 9/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6076 - loss: 0.9303
Epoch 10/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6309 - loss: 0.8925
Epoch 11/100
181/181 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6743 - loss: 0.8613
Epoch 12/100
181/181 ━━━━━━━━

In [8]:
y_pred=model.predict(X_test)
y_pred_int=np.argmax(y_pred, axis=1)
y_test_int=np.argmax(y_test, axis=1)
cm=confusion_matrix(y_test_int, y_pred_int)
print(cm)

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 796us/step
[[411   7   2   5]
 [  0  49   3   2]
 [ 32  16 122   4]
 [  1   0   0 121]]


In [10]:
# %pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.
